version: '3'
services:
    web:
        image: nginx:alpine
        volumes:
            - "./code:/var/www/demo"
            - "./etc/nginx/nginx.conf:/etc/nginx/nginx.conf"
            - "${WEB_CODE_DIR}:/var/www/code"
            - "./logs/nginx:/etc/nginx/logs"
            - "./etc/nginx/vhosts:/etc/nginx/vhosts"
        ports:
            - "80:80"
            - "443:443"
        command: /bin/sh -c "nginx -g 'daemon off;'"
        restart: always
        depends_on:
            - php
            - redis
            - php5
            - mysql
    php:
        build: ./php
        restart: always
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "${WEB_CODE_DIR}:/var/www/code"
            - "./code:/var/www/demo"
    php5:
        build: ./php5
        restart: always
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "${WEB_CODE_DIR}:/var/www/code"
    redis:
        build: ./redis
        ports:
            - "${REDIS_PORT}:6379"
        volumes:
            - "./redis/tmp/data:/data"
        restart: always
    mysql:
        image: mysql:5.7
        volumes:
            - "./etc/mysql/conf/my.cnf:/etc/mysql/my.cnf"
            - "./mysql/logs:/logs"
            - "./mysql/data:/var/lib/mysql"
        environment:
            - MYSQL_ROOT_PASSWORD=123456
        ports:
          - "3306:3306"
        restart: always
